export const mockStats = {
    checkInsToday:  3,
    checkOutsToday: 2,
    occupancy:      { occupied: 8, total: 14 },
    monthRevenue:   4820,
}

export const mockCheckIns = [
    { id: 1, guestName: 'Παπαδόπουλος Γιώργης', room: '101', nights: 3 },
    { id: 2, guestName: 'Smith John',            room: '203', nights: 5 },
    { id: 3, guestName: 'Müller Klaus',          room: '305', nights: 2 },
]

export const mockCheckOuts = [
    { id: 4, guestName: 'Γεωργίου Μαρία', room: '102', total: 240 },
    { id: 5, guestName: 'Johnson Lisa',   room: '204', total: 450 },
]

export const mockRooms = [
    // Ισόγειο
    { id: 13, number: 13, type: 'Οικογενειακό', floor: 0, capacity: 4, hasKitchen: false, status: 'available', notes: '' },
    { id: 14, number: 14, type: 'Οικογενειακό', floor: 0, capacity: 4, hasKitchen: false, status: 'available', notes: '' },

    // 1ος όροφος
    { id: 1,  number: 1,  type: 'Τρίκλινο',     floor: 1, capacity: 3, hasKitchen: true,  status: 'available', notes: '' },
    { id: 2,  number: 2,  type: 'Τρίκλινο',     floor: 1, capacity: 3, hasKitchen: true,  status: 'available', notes: '' },
    { id: 3,  number: 3,  type: 'Δίκλινο',      floor: 1, capacity: 2, hasKitchen: false, status: 'available', notes: '' },
    { id: 4,  number: 4,  type: 'Δίκλινο',      floor: 1, capacity: 2, hasKitchen: true,  status: 'available', notes: '' },
    { id: 5,  number: 5,  type: 'Δίκλινο',      floor: 1, capacity: 2, hasKitchen: true,  status: 'available', notes: '' },
    { id: 6,  number: 6,  type: 'Τρίκλινο',     floor: 1, capacity: 3, hasKitchen: true,  status: 'available', notes: '' },

    // 2ος όροφος
    { id: 7,  number: 7,  type: 'Τρίκλινο',     floor: 2, capacity: 3, hasKitchen: false, status: 'available', notes: '' },
    { id: 8,  number: 8,  type: 'Δίκλινο',      floor: 2, capacity: 2, hasKitchen: false, status: 'available', notes: '' },
    { id: 9,  number: 9,  type: 'Δίκλινο',      floor: 2, capacity: 2, hasKitchen: false, status: 'available', notes: '' },
    { id: 10, number: 10, type: 'Δίκλινο',      floor: 2, capacity: 2, hasKitchen: false, status: 'available', notes: '' },
    { id: 11, number: 11, type: 'Δίκλινο',      floor: 2, capacity: 2, hasKitchen: false, status: 'available', notes: '' },
]

export const mockGuests = [
    {
        id: 1,
        firstName: 'Γιώργης',
        lastName: 'Παπαδόπουλος',
        email: 'gpapadopoulos@email.com',
        phone: '+30 697 1234567',
        nationality: 'GR',
        idNumber: 'ΑΒ123456',
        notes: 'Προτιμά δωμάτιο με θέα',
        createdAt: '2024-01-15',
    },
    {
        id: 2,
        firstName: 'John',
        lastName: 'Smith',
        email: 'john.smith@email.com',
        phone: '+44 7911 123456',
        nationality: 'GB',
        idNumber: 'P123456789',
        notes: '',
        createdAt: '2024-02-20',
    },
    {
        id: 3,
        firstName: 'Klaus',
        lastName: 'Müller',
        email: 'klaus.muller@email.com',
        phone: '+49 151 12345678',
        nationality: 'DE',
        idNumber: 'C01X00T47',
        notes: 'Αλλεργία στη γλουτένη',
        createdAt: '2024-03-10',
    },
    {
        id: 4,
        firstName: 'Μαρία',
        lastName: 'Γεωργίου',
        email: 'mgeorgiou@email.com',
        phone: '+30 694 9876543',
        nationality: 'GR',
        idNumber: 'ΑΚ789012',
        notes: '',
        createdAt: '2024-04-05',
    },
    {
        id: 5,
        firstName: 'Lisa',
        lastName: 'Johnson',
        email: 'lisa.j@email.com',
        phone: '+1 555 0123456',
        nationality: 'US',
        idNumber: 'P987654321',
        notes: 'Late check-in συνήθως',
        createdAt: '2024-05-18',
    },
]

export const mockBookings = [
    {
        id: 1,
        guestId: 1,
        guestName: 'Παπαδόπουλος Γιώργης',
        roomId: 1,
        roomNumber: 1,
        checkIn: '2026-04-28',
        checkOut: '2026-05-01',
        nights: 3,
        adults: 2,
        children: 0,
        status: 'checked_in',
        source: 'frontdesk',
        totalAmount: 360,
        depositAmount: 100,
        depositDate: '2026-04-10',
        paidAmount: 100,
        paymentStatus: 'deposit',
        notes: 'Προτιμά δωμάτιο με θέα',
        extras: [],
    },
    {
        id: 2,
        guestId: 2,
        guestName: 'Smith John',
        roomId: 3,
        roomNumber: 3,
        checkIn: '2026-04-30',
        checkOut: '2026-05-05',
        nights: 5,
        adults: 2,
        children: 0,
        status: 'confirmed',
        source: 'booking_com',
        totalAmount: 500,
        depositAmount: 0,
        depositDate: null,
        paidAmount: 0,
        paymentStatus: 'unpaid',
        notes: '',
        extras: [],
    },
    {
        id: 3,
        guestId: 3,
        guestName: 'Müller Klaus',
        roomId: 6,
        roomNumber: 6,
        checkIn: '2026-04-25',
        checkOut: '2026-04-29',
        nights: 4,
        adults: 3,
        children: 1,
        status: 'checked_out',
        source: 'booking_com',
        totalAmount: 480,
        depositAmount: 480,
        depositDate: '2026-04-01',
        paidAmount: 480,
        paymentStatus: 'paid',
        notes: 'Αλλεργία στη γλουτένη',
        extras: [
            { id: 1, description: 'Πρωινό', pricePerDay: 10, days: 4, total: 40 },
        ],
    },
    {
        id: 4,
        guestId: 4,
        guestName: 'Γεωργίου Μαρία',
        roomId: 8,
        roomNumber: 8,
        checkIn: '2026-05-01',
        checkOut: '2026-05-03',
        nights: 2,
        adults: 2,
        children: 0,
        status: 'confirmed',
        source: 'phone',
        totalAmount: 160,
        depositAmount: 50,
        depositDate: '2026-04-20',
        paidAmount: 50,
        paymentStatus: 'deposit',
        notes: '',
        extras: [],
    },
    {
        id: 5,
        guestId: 5,
        guestName: 'Johnson Lisa',
        roomId: 13,
        roomNumber: 13,
        checkIn: '2026-05-05',
        checkOut: '2026-05-12',
        nights: 7,
        adults: 2,
        children: 2,
        status: 'confirmed',
        source: 'booking_com',
        totalAmount: 980,
        depositAmount: 200,
        depositDate: '2026-04-15',
        paidAmount: 200,
        paymentStatus: 'deposit',
        notes: 'Late check-in',
        extras: [
            { id: 2, description: 'Μεταφορά αεροδρόμιο', pricePerDay: 0, days: 1, total: 50 },
        ],
    },
]